### PR TITLE
DiscordJS Version 13, v3.0.0 - v.3.6.1

### PR DESCRIPTION
**Pull request by TeraBaito**
YEAHHHH IM FINALLY MERGING THIS BRANCH やったああああぁぁぁーーーーーーーーーーー
a LOT of shit

Align with all the new DJS v13 breaking changes, those mostly being
- Node v16 **REQUIRED** (it was Node 14, but idk they used some AbortController shit and now it's 16 👍)
(I almost shit myself thinking sqlite3 would not be able to install in Node 16 but it worked thankfully)
- Embeds enforcing strings
- Sending messages with embeds has changed
- `GuildMember#hasPermission` getting removed
- Intents, intents, intents; `ClientOptions#fetchAllMembers` also got removed so I wasted A TON patching functions to fetch needed users and using caches, partials, etc. to my advantage
- `Client#message` => `Client#messageCreate`
- `whateverID` => `whateverId`
- Changes on message collector syntax
- `Message#delete` `timeout` option removed (which I had prepared for before)
- [...and a lot more](https://discordjs.guide/additional-info/changes-in-v13.html)
Also take advantage of the new API shit like querying members by their names (on `nicknameProcess`)
Also also use the new `@discordjs/builders` module (just recently, they make cool shit)

Use buttons instead of reactions as prompts! Buttons are a great feature that can be bundled in with more stability and effectiveness. They don't require to use a slash command reply, so it's great for normal commands as well!

Start with slash commands! Discord brought up this amazing (and a bit weird to use) feature that turned into great customization about your elements on a command, to make them more accessible and structured through a panel bundled to the Discord client.  I made an interactions publisher ~(which Max stole)~, a separate interactions handler and folder, and a simple but effective structure for the slashies so they can be published and ran easily! I made a `toggle` command to turn on and off slashies (which only staff can use), and I bundled a few existing "normal" commands to the folder.

A WAY BETTER blacklisting. The nifty progress can be seen [here](https://github.com/TeraBaito/jaidens-discord-utilities/issues/4), but to summarize: I removed the "pluralizer" (check with "s" at the end of a word) because it was causing too much trouble; symbol checking won't override the start-to-end checking; symbols will escape when added through `a+addword`, a better multi-word blacklisting that'll manually check blacklisting in every word by substrings in the sentence (I swear this took me long to figure out).

Refactoring a lot (most) commands, cleaning them, fixing their help strings, adding and removing stuff, having to fix NEARLY ALL MOD COMMANDS (god i hate those), fixfixfix refactorrefactorrefactor etc
I make better code and slack harder, Max makes more code and copes harder

Welcome messages now follow the nice! funky! cool! new! epic! Double Counter verification (sarcasm ofc I fucking hate it). A member will be greeted when **they just got their verification role removed and their member role added**. It'll still unhoist them and log their info at normal join, and `guildMemberRemove` will work normally.
(so there was this one time it started pinging everyone whose data changed? y'know, because it's `guildMemberUpdate`... that was funny as hell and took me days to fix)

Tags can be made staff only by using the `staff` argument on `a+addtag`. more hidden stuff yay!
oh also the tags can be listed with pagination by using `a+listtags`

- [x] I have tested each and every command. They could still be prone (I checked for edge cases too), but for the most part should be good to go and will hear the bugs as they come along.
- [ ] I **haven't** tested each and every event, but I'm quite certain they're all working. If something broke, it's probably the configs.
- [x] I have tested each and every slash command. Same situation as normal commands.
- [x] I have tested most of the other things, functions, etc. The most troublesome func would probably be `getMember()`, and the inner workings of it have been successfully patched (how it's called and used might've not, so I'll have to see those bugs as they come over time)
- [x] I have drank water while doing this PR, in fact I just sipped as I'm writing this sentence.

### Tofu Bot disband
As more of the "sentimental" part, around a week or two ago, one small joke on the r/JaidenAnimations server having to do with eval and YuriGroove and the server icon turned into an incident in which Tofu Bot was revoked from its permissions, making Max (its owner) kick the bot from the server and scrap its presence on it. That's probably why you can see a branch called `max-pr` with the latest commit being "Remove Tofu". However, very recently Tofu got reinvited! With admin again as well, to not cause any issue with the bot workings (which was the main reason why it got kicked, the perms purge broke a lot IF NOT ALL Tofu). This story ends with a good ending for now, expecting to keep the collab with Max, the code discussion and the overall ying and yang of our two "Jaiden bots".

That's about it, I'm so happy I am finally able to merge this mf. A lot of work (28 commits LOL) were put into this, and seeing it in the master branch just means going to the moon. To the moon!!!!! 🚀🚀🚀

This PR is doing to be in draft because it's not ready for review. I'm going to fix the conflicts, rebase some shit probably, squash some changes together probably, and let Max have its final thoughts on it, then review and merge. Enjoy the view over at Mount Chirripó!

### CODE REVIEW

**Comment by TeraBaito** [comment]
wtf is codefactor talking about
how do i fix a "Complex Method" LMAO what

**Comment by TeraBaito** [comment]
Fixed codefactor score by ignoring issues like that
Ignorance is bliss.

**Comment by MaxTechnics** [comment]
If you're going to request me to review maybe idk give time. If you're going to request review only to merge literally a minute later. I can't read trough 5k+ lines of changes in less than a minute lamo

**Comment by MaxTechnics** [comment]
ok nevermind i'm blind

**Review by MaxTechnics — COMMENTED** [review]
Ok so even though i'm late. ( I genuinely got the notification for removal of me as reviewer but not the request for some reason)

Not sure why you'd want me to review this. You write the better code out of us. Nothing i can say really. Maybe 'createtag' 'tagcreate' as aliases for the addtag command, and outside of github crying for some final newlines at the end of file, i really can't say anything about this.

**Pull request merged**
