### PR TITLE
Fix mass ping vulnerability

### LINKED ISSUE #13: Bean command allows @everyone and @here pinging
Example: a+bean @everyone

### PR DESCRIPTION
**Pull request by MaxTechnics**
Fixes #13

Replaces mass pings, being roles, @\here and @\everyone with a non pinging string.

### CODE REVIEW

**Comment by TeraBaito** [comment]
I told you I didn't want it like this

**Comment by TeraBaito** [comment]
wow i have 14 prs already incredible

**Comment by MaxTechnics** [comment]
k
also that's not how #id's work. You have 7pr and 7issues dumbass

**Comment by TeraBaito** [comment]
D:

**Pull request merged**
